[input]
data_tag = 'v0.5.1_v03'
observed_source = 'Mrk 421'
columns_to_read = ['alt_tel', 'az_tel', 'dragon_time', 'gammaness', 'intensity', 'leakage2_intensity', 'n_pixels', 'reco_src_x', 'reco_src_y', 'wl']

[output]
interactive = true
directory = '/tmp'

[preselection]
intensity = [100, 1000000]
leakage2_intensity = [0.0, 0.1]
wl = [0.0, 1.0]    # 0.01
gammaness = [0.8, 1.0]
n_pixels = [0, 1800]    # 1800

[analysis]
type = 'wobble'
runs = [2130, 2131, 2132, 2133]   # runs to be analysed
[analysis.parameters]
n_points = 4
[analysis.selection]
theta2 =  [0.1, 0.5, 2.0] # cut, normalization range min, normalization range max

[plot_style]
[plot_style.figure]
figsize = 12
[plot_style.font]
size = 20
